const SELECTORS = {
  HIPPO_ED: {
    ACCOUNT_SETTINGS: {
      $accountSettingsNav: $('[href="/hippo-ed/work-hive/dist/account-settings/general"]'),
      $billingAddress: $('#billing_address'),
      $billingCity: $('#billing_city'),
      $billingZip: $('#billing_zip'),
      $commentsAlias: $('.comments-alias input'),
      $commentsEmail: $('.comments-email input'),
      $firstName: $('#first_name'),
      $lastName: $('.profile-lastname input'),
      $suffix: $('.profile-suffix input'),
      $profilePhone: $('.profile-phone input'),
      $professionInstitution: $('.profession-institution input'),
      $settingsSubmit: $('[type="submit"]'),
      $shippingAddress: $('#shipping_address'),
      $shippingCity: $('#shipping_city'),
      $shippingZip: $('#shipping_zip'),
      $submitSuccess: $('div.alert.alert-success'),
    },
    SIGN_IN: {
      $emailInput: $('#email'),
      $emailWarning: $('.email small'),
      $passwordInput: $('#password'),
      $passwordWarning: $('.password small'),
      $signin: $('[value="Sign In"]'),
      $signinNav: $('[href="/hippo-ed/work-hive/dist/signin"]'),
      $signOut: $('[href="#sign-out"]'),
    },
  },
  PCRAP: {
    SUBSCRIBE: {
      $subscribe: $('[href="subscribe"]'),
      $agree: $('[value="I Agree"]'),
      $order: $('[value="Place Order"]'),
      $episode: $('a.episode-guide-episode'),
      $email: $('#email'),
      $physician: $('[for="subscription_type_1"]'),
      $cardNumber: $('#card_number'),
      $cardMonth: $('#card_expiry_month'),
      $cardYear: $('#card_expiry_year'),
      $CVV: $('#card_verification_value'),
      $billing_first: $('#billing_address_first_name'),
      $billing_last: $('#billing_address_last_name'),
      $billing_address1: $('#billing_address_line1'),
      $billing_city: $('#billing_address_city'),
      $billing_state: $('#billing_address_provstate_flydown'),
      $billing_zip: $('#billing_address_postalcode'),
      $first_name: $('#first_name'),
      $last_name: $('#last_name'),
      $suffix: $('#suffix'),
      $password: $('#password'),
      $continue: $('#continue_button'),
      $profession_option: $('#profession-option_1'),
      $get_started: $('[value="Ok, let’s get started"]'),
      $upgrade_button: $('.upgrade-button'),
      $gravatarName: $('.gravatar-name'),
      $subscription_option: $('[for="subscription_type_1"]'),
    },
  },
  EEM: {
    $register: $('[href="course/2017"]'),
    $register2: $('#purchase_button_51'),
    $first_name: $('#first_name'),
    $last_name: $('#last_name'),
    $email: $('#email'),
    $password: $('#password'),
    $confirmEmail: $('#confirm_email'),
    $billing_first: $('#billing_address_first_name'),
    $billing_last: $('#billing_address_last_name'),
    $billing_address1: $('#billing_address_line1'),
    $billing_city: $('#billing_address_city'),
    $billing_state: $('#billing_address_provstate_flydown'),
    $billing_zip: $('#billing_address_postalcode'),
    $cardNumber: $('#card_number'),
    $cardMonth: $('#card_expiry_month'),
    $cardYear: $('#card_expiry_year'),
    $CVV: $('#card_verification_value'),
    $card_name: $('#card_fullname'),
    $submit_button: $('#submit_button'),
    $order: $('[value="Place Order"]'),
  }
};

module.exports = SELECTORS;
